version: '3.8'
services:
  bot:
    build: .
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    expose:
      - "6379"
